apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: dev
  labels:
    app: my-app
    environment: dev
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
